### PR TITLE
Add Vultr provider

### PR DESCRIPTION
**Pull request by anbraten**

### CODE REVIEW

**Comment by guisea** [comment]
I made a working vultr provider a while back.  Just wondering if anyone is working on this/sorted or I might be able to contribute some work to this PR although not sure how to manage that?

**Comment by anbraten** [comment]
Would be great to finish it. You might open a new PR to the repo or you could point me to your changes so I can add them.

**Comment by guisea** [comment]
I just started digging it out last night.  There was a final piece I was still working on regards to the SSH key.  

I will locate it and  finish that up.  Will create a new PR for this too I think.

**Comment by guisea** [comment]
@anbraten Created new PR which has a working driver for VULTR #88

**Pull request closed without merging**
